"""Increase password_hash length

Revision ID: 40214b60a9b7
Revises: 7389a675f178
Create Date: 2025-09-15 12:39:48.062716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40214b60a9b7'
down_revision = '7389a675f178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
